/* =============================================================
   AI INSIGHTS.JS — AI Risk Dashboard & Clinical Analysis
   ============================================================= */

function renderAIInsights(container) {
    if (!Auth.requireAuth()) return;
    const alerts = DB.getAll('aiAlerts').sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt));
    const unacked = alerts.filter(a => !a.acknowledged);
    const patients = DB.getAll('patients').filter(p => !p.isDeleted && p.status !== 'discharged');

    container.innerHTML = `
    <div class="fade-in">
      <div class="page-header">
        <div class="page-header-left">
          <h1>🤖 AI Clinical Insights</h1>
          <p>AI-powered risk analysis and clinical decision support</p>
        </div>
        <div class="page-header-actions">
          <button class="btn btn-ai" onclick="runAllAnalysis()">⚡ Analyze All Patients</button>
          ${unacked.length > 0 ? `<button class="btn btn-secondary" onclick="acknowledgeAll()">✅ Acknowledge All</button>` : ''}
        </div>
      </div>

      <!-- AI Disclaimer -->
      <div class="ai-disclaimer" style="margin-bottom:20px">
        🤖 <strong>AI for Clinical Decision Support Only</strong> — These insights are generated by a rules-based clinical AI. They assist but do not replace physician diagnosis and clinical judgment. All decisions remain with the treating physician.
      </div>

      <!-- Alert Summary Stats -->
      <div class="stats-grid" style="margin-bottom:24px">
        <div class="stat-card" style="--stat-color:#ef4444">
          <div class="stat-icon">🚨</div>
          <div class="stat-value">${alerts.filter(a => a.riskLevel === 'high' && !a.acknowledged).length}</div>
          <div class="stat-label">High Risk Active</div>
        </div>
        <div class="stat-card" style="--stat-color:#f59e0b">
          <div class="stat-icon">⚠️</div>
          <div class="stat-value">${alerts.filter(a => a.riskLevel === 'medium' && !a.acknowledged).length}</div>
          <div class="stat-label">Medium Risk Active</div>
        </div>
        <div class="stat-card" style="--stat-color:#10b981">
          <div class="stat-icon">✅</div>
          <div class="stat-value">${alerts.filter(a => a.acknowledged).length}</div>
          <div class="stat-label">Acknowledged</div>
        </div>
        <div class="stat-card" style="--stat-color:#a855f7">
          <div class="stat-icon">🔬</div>
          <div class="stat-value">${alerts.length}</div>
          <div class="stat-label">Total Analyses</div>
        </div>
      </div>

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:24px">
        <!-- Active Alerts -->
        <div class="card">
          <div class="card-header">
            <div><div class="card-title">🚨 Active Risk Alerts</div><div class="card-subtitle">${unacked.length} unacknowledged</div></div>
          </div>
          ${unacked.length ? unacked.map(a => `
            <div class="alert-banner alert-${a.riskLevel}" style="margin-bottom:10px">
              <span class="alert-icon">${a.riskLevel === 'high' ? '🚨' : a.riskLevel === 'medium' ? '⚠️' : 'ℹ️'}</span>
              <div class="alert-body">
                <div class="alert-title">${Utils.escapeHtml(a.patientName)} — Score: ${a.riskScore}/100</div>
                <div class="alert-desc">${(a.patterns || []).slice(0, 2).map(p => Utils.escapeHtml(p)).join(' · ')}</div>
                <div style="margin-top:6px;display:flex;gap:6px;flex-wrap:wrap">
                  ${(a.suggestedDiagnoses || []).slice(0, 2).map(d => `<span style="background:rgba(168,85,247,0.1);color:var(--ai-purple);border-radius:4px;padding:2px 8px;font-size:10px">${Utils.escapeHtml(d)}</span>`).join('')}
                </div>
                <div class="alert-time">${Utils.timeAgo(a.generatedAt)}</div>
              </div>
              <div style="display:flex;flex-direction:column;gap:6px">
                <span class="badge badge-${a.riskLevel}">${Utils.capitalize(a.riskLevel)}</span>
                <button class="btn btn-sm btn-secondary" onclick="acknowledgeAlert('${a.id}')">✓</button>
              </div>
            </div>
          `).join('') : '<div class="empty-state"><div class="empty-icon">✅</div><h3>No active alerts</h3><p>All patients within safe parameters</p></div>'}
        </div>

        <!-- Patient Risk Overview -->
        <div class="card">
          <div class="card-header">
            <div><div class="card-title">📊 Patient Risk Overview</div><div class="card-subtitle">Click to analyze</div></div>
          </div>
          <div style="display:flex;flex-direction:column;gap:10px">
            ${patients.map(p => {
        const latestAlert = DB.getPatientAlerts(p.id)[0];
        const score = latestAlert ? latestAlert.riskScore : null;
        const level = latestAlert ? latestAlert.riskLevel : null;
        const vitals = DB.getPatientVitals(p.id);
        return `
                <div style="display:flex;align-items:center;gap:10px;padding:10px;background:var(--bg-input);border-radius:8px;cursor:pointer" onclick="analyzePatientDetail('${p.id}')">
                  <div class="avatar" style="width:34px;height:34px;border-radius:8px;background:${Utils.roleGradient('doctor')};display:flex;align-items:center;justify-content:center;font-weight:700;font-size:12px;flex-shrink:0">${Utils.initials(p.name)}</div>
                  <div style="flex:1;min-width:0">
                    <div style="font-weight:600;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${Utils.escapeHtml(p.name)}</div>
                    <div style="font-size:10px;color:var(--text-muted)">${p.department} · ${vitals.length} vitals</div>
                  </div>
                  ${score !== null ? `
                    <div style="text-align:center">
                      <div style="font-family:var(--font-mono);font-weight:800;font-size:18px;color:${level === 'high' ? 'var(--danger)' : level === 'medium' ? 'var(--warning)' : 'var(--success)'}">${score}</div>
                      <div style="font-size:9px;text-transform:uppercase;color:var(--text-muted)">Risk</div>
                    </div>
                  ` : '<button class="btn btn-sm btn-ai" style="font-size:10px;padding:4px 8px">Analyze</button>'}
                </div>
              `;
    }).join('')}
          </div>
        </div>
      </div>

      <!-- Drug Interaction Knowledge Base -->
      <div class="card">
        <div class="card-header">
          <div><div class="card-title">💊 Known Drug Interaction Reference</div><div class="card-subtitle">Auto-checked during prescription</div></div>
        </div>
        <div class="table-wrapper">
          <table class="data-table">
            <thead><tr><th>Drug 1</th><th>Drug 2</th><th>Severity</th><th>Description</th></tr></thead>
            <tbody>
              ${AI.DRUG_INTERACTIONS.slice(0, 6).map(d => `
                <tr>
                  <td>${Utils.capitalize(Utils.escapeHtml(d.drug1))}</td>
                  <td>${Utils.capitalize(Utils.escapeHtml(d.drug2))}</td>
                  <td><span class="badge badge-${d.risk === 'Major' ? 'high' : 'medium'}">${d.risk}</span></td>
                  <td style="font-size:12px;color:var(--text-secondary)">${Utils.escapeHtml(d.description)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `;

    window.runAllAnalysis = function () {
        Utils.toast('🤖 Analyzing all active patients...', 'ai', 3000);
        let analyzed = 0;
        patients.forEach(p => {
            AI.analyzePatient(p.id);
            analyzed++;
        });
        setTimeout(() => {
            Utils.toast(`✅ Analyzed ${analyzed} patients. Alerts updated.`, 'success');
            renderAIInsights(container);
        }, 1500);
    };

    window.acknowledgeAlert = function (alertId) {
        DB.update('aiAlerts', alertId, { acknowledged: true });
        DB.log('ACK_ALERT', `Alert ${alertId} acknowledged`);
        Utils.toast('Alert acknowledged.', 'success');
        renderAIInsights(container);
    };

    window.acknowledgeAll = function () {
        unacked.forEach(a => DB.update('aiAlerts', a.id, { acknowledged: true }));
        DB.log('ACK_ALL_ALERTS', `All ${unacked.length} alerts acknowledged`);
        Utils.toast(`${unacked.length} alerts acknowledged.`, 'success');
        renderAIInsights(container);
    };

    window.analyzePatientDetail = function (patientId) {
        Utils.toast('🤖 Running AI analysis...', 'ai', 1500);
        setTimeout(() => {
            const result = AI.analyzePatient(patientId);
            if (!result) return;
            const { patient, riskScore, riskLevel, patterns, suggestions, drugInteractions, readmissionRisk } = result;
            Utils.showModal(`
        <div class="modal-header">
          <div><h3 class="modal-title">🤖 AI Analysis — ${Utils.escapeHtml(patient.name)}</h3></div>
          <button class="modal-close" onclick="Utils.closeModal()">✕</button>
        </div>
        <div class="ai-disclaimer">AI for clinical decision support only. Does not replace physician judgment.</div>
        <div style="display:flex;gap:16px;margin:16px 0;align-items:flex-start;flex-wrap:wrap">
          <div class="risk-score-widget">
            <div class="risk-score-circle risk-${riskLevel}">
              <div class="risk-score-num">${riskScore}</div>
              <div class="risk-score-text">/100</div>
            </div>
            <div class="risk-label" style="color:${riskLevel === 'high' ? 'var(--danger)' : riskLevel === 'medium' ? 'var(--warning)' : 'var(--success)'}">${Utils.capitalize(riskLevel)} Risk</div>
            <div style="font-size:11px;color:var(--text-muted);margin-top:6px">Readmission: <strong>${Utils.capitalize(readmissionRisk)}</strong></div>
          </div>
          <div style="flex:1;min-width:200px">
            <div style="font-size:12px;font-weight:700;color:var(--text-muted);text-transform:uppercase;margin-bottom:8px">Clinical Patterns Detected</div>
            ${patterns.length ? patterns.map(p => `<div style="font-size:13px;padding:5px 0;border-bottom:1px solid var(--border)">${Utils.escapeHtml(p)}</div>`).join('') : '<div style="color:var(--text-muted);font-size:13px">No warning patterns</div>'}
          </div>
        </div>
        ${suggestions.length ? `
          <div class="ai-insight-card" style="margin-bottom:12px">
            <div class="ai-badge">🩺 Differential Diagnoses (AI)</div>
            ${suggestions.map(s => `<div style="padding:5px 0;border-bottom:1px solid rgba(255,255,255,0.05);font-size:13px"><strong>${Utils.escapeHtml(s.diagnosis)}</strong> — ${Utils.escapeHtml(s.confidence)} · ${Utils.escapeHtml(s.reason)}</div>`).join('')}
          </div>
        ` : ''}
        ${drugInteractions.length ? `<div style="background:rgba(239,68,68,0.08);border:1px solid rgba(239,68,68,0.3);border-radius:8px;padding:12px"><div style="font-size:12px;font-weight:700;color:var(--danger);margin-bottom:6px">⚠️ Drug Interactions</div>${drugInteractions.map(d => `<div style="font-size:12.5px">${Utils.capitalize(d.risk)}: ${d.drug1} + ${d.drug2}</div>`).join('')}</div>` : ''}
      `, 'modal-lg');
            renderAIInsights(container);
        }, 800);
    };
}
